# Generated by Django 5.1.6 on 2025-03-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bot",
            old_name="name",
            new_name="bot_username",
        ),
        migrations.RenameField(
            model_name="bot",
            old_name="owner",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="token",
        ),
        migrations.AddField(
            model_name="bot",
            name="bot_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
