repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --config ./.github/config/.black .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: isort
        name: isort
        entry: isort --settings-file ./.github/config/.isort.cfg . --profile black --filter-files
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config ./.github/config/.flake8 .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy
        args: [ '--config-file', '.github/config/mypy.ini', '--ignore-missing-imports']
        language: system
        types: [ python ]