"""Add secret_token middleware

Revision ID: 279547ea5e39
Revises: 84814483d430
Create Date: 2025-02-22 18:50:25.627136

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "279547ea5e39"
down_revision: Union[str, None] = "84814483d430"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bots", sa.Column("secret_token", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bots", "secret_token")
    # ### end Alembic commands ###
