"""Init

Revision ID: 0e27e02c9007
Revises:
Create Date: 2025-03-01 09:48:15.728586

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0e27e02c9007"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("secret_token", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bots_id"), "bots", ["id"], unique=False)
    op.create_index(op.f("ix_bots_token"), "bots", ["token"], unique=True)
    op.create_table(
        "commands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("command", sa.String(), nullable=True),
        sa.Column("response", sa.String(), nullable=True),
        sa.Column("bot_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["bots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_commands_id"), "commands", ["id"], unique=False)
    op.create_table(
        "funnels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("bot_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["bots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_funnels_id"), "funnels", ["id"], unique=False)
    op.create_table(
        "funnel_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("funnel_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["funnel_id"],
            ["funnels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_funnel_steps_id"), "funnel_steps", ["id"], unique=False
    )
    op.create_table(
        "buttons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("next_step_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["next_step_id"],
            ["funnel_steps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["funnel_steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_buttons_id"), "buttons", ["id"], unique=False)
    op.create_table(
        "user_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("bot_id", sa.Integer(), nullable=True),
        sa.Column("funnel_id", sa.Integer(), nullable=True),
        sa.Column("current_step_id", sa.Integer(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_step_id"],
            ["funnel_steps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["funnel_id"],
            ["funnels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_states_id"), "user_states", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_states_id"), table_name="user_states")
    op.drop_table("user_states")
    op.drop_index(op.f("ix_buttons_id"), table_name="buttons")
    op.drop_table("buttons")
    op.drop_index(op.f("ix_funnel_steps_id"), table_name="funnel_steps")
    op.drop_table("funnel_steps")
    op.drop_index(op.f("ix_funnels_id"), table_name="funnels")
    op.drop_table("funnels")
    op.drop_index(op.f("ix_commands_id"), table_name="commands")
    op.drop_table("commands")
    op.drop_index(op.f("ix_bots_token"), table_name="bots")
    op.drop_index(op.f("ix_bots_id"), table_name="bots")
    op.drop_table("bots")
    # ### end Alembic commands ###
