"""Change bots column

Revision ID: 142ffa79c748
Revises: 2c2f162274d7
Create Date: 2025-03-04 06:28:07.730026

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "142ffa79c748"
down_revision: Union[str, None] = "2c2f162274d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bots", sa.Column("username", sa.String(), nullable=True))
    op.drop_column("bots", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bots",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("bots", "username")
    # ### end Alembic commands ###
