"""Fix main_menu field

Revision ID: 14de7b9f6b95
Revises: b155eafa2da8
Create Date: 2025-03-08 15:39:54.889074

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "14de7b9f6b95"
down_revision: Union[str, None] = "b155eafa2da8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "main_menu",
        "welcome_message",
        existing_type=sa.VARCHAR(length=3000),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "main_menu",
        "welcome_message",
        existing_type=sa.VARCHAR(length=3000),
        nullable=False,
    )
    # ### end Alembic commands ###
