"""Set nullable=True for next steps

Revision ID: 18823ad12e42
Revises: 9b5e734111fd
Create Date: 2025-03-26 16:09:48.920553

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "18823ad12e42"
down_revision: Union[str, None] = "9b5e734111fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
