"""Add-is-active-filed-to-Bot

Revision ID: 2c2f162274d7
Revises: 0e27e02c9007
Create Date: 2025-03-02 09:50:51.074301

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2c2f162274d7"
down_revision: Union[str, None] = "0e27e02c9007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bots", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bots", "is_active")
    # ### end Alembic commands ###
