"""fix bot user id

Revision ID: 34d1f1d83776
Revises: 4669ba4212e7
Create Date: 2025-04-07 09:51:38.009782

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "34d1f1d83776"
down_revision: Union[str, None] = "4669ba4212e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bot_users", sa.Column("user_id", sa.BigInteger(), nullable=False)
    )
    op.drop_index("idx_bot_user_unique", table_name="bot_users")
    op.create_index(
        "idx_bot_user_unique",
        "bot_users",
        ["bot_id", "user_id"],
        unique=True,
        schema="public",
    )
    op.drop_constraint(
        "bot_users_bot_id_fkey", "bot_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        source_schema="public",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bot_users", schema="public", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "bot_users_bot_id_fkey",
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        "idx_bot_user_unique", table_name="bot_users", schema="public"
    )
    op.create_index(
        "idx_bot_user_unique", "bot_users", ["bot_id", "id"], unique=True
    )
    op.drop_column("bot_users", "user_id")
    # ### end Alembic commands ###
