"""Fix chain relationship

Revision ID: 457df28faa66
Revises: 8759c94d0e89
Create Date: 2025-03-21 09:50:45.624368

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "457df28faa66"
down_revision: Union[str, None] = "8759c94d0e89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "chains_first_chain_step_id_fkey", "chains", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "chains",
        "chain_steps",
        ["first_chain_step_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chains", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "chains_first_chain_step_id_fkey",
        "chains",
        "chain_steps",
        ["first_chain_step_id"],
        ["id"],
    )
    # ### end Alembic commands ###
