"""Fix main menu2

Revision ID: 4669ba4212e7
Revises: f3b6895820c8
Create Date: 2025-04-06 08:14:09.150584

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4669ba4212e7"
down_revision: Union[str, None] = "f3b6895820c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "bot_users_bot_id_fkey", "bot_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        source_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "buttons_main_menu_id_fkey", "buttons", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "buttons",
        "main_menu",
        ["main_menu_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "main_menu_bot_id_fkey", "main_menu", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "main_menu", "bots", ["bot_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "main_menu", type_="foreignkey")  # type:ignore
    op.create_foreign_key(
        "main_menu_bot_id_fkey", "main_menu", "bots", ["bot_id"], ["id"]
    )
    op.drop_constraint(None, "buttons", type_="foreignkey")  # type:ignore
    op.create_foreign_key(
        "buttons_main_menu_id_fkey",
        "buttons",
        "main_menu",
        ["main_menu_id"],
        ["id"],
    )
    op.drop_constraint(
        None, "bot_users", schema="public", type_="foreignkey"  # type:ignore
    )  # type:ignore
    op.create_foreign_key(
        "bot_users_bot_id_fkey",
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
