"""Add indexes

Revision ID: 540fc0e1afed
Revises: fa1b12f9b03d
Create Date: 2025-04-19 12:38:31.531651

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "540fc0e1afed"
down_revision: Union[str, None] = "fa1b12f9b03d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_botuser_created_at", "bot_users", ["created_at"], unique=False
    )
    op.drop_index("ix_bots_token", table_name="bots")
    op.create_index("idx_bot_token", "bots", ["token"], unique=True)
    op.create_index("idx_bot_username", "bots", ["username"], unique=False)
    op.create_unique_constraint(None, "bots", ["token"])
    op.create_index(
        "idx_button_bot_text",
        "buttons",
        ["bot_id", "button_text"],
        unique=False,
    )
    op.create_index("idx_button_chain", "buttons", ["chain_id"], unique=False)
    op.create_index(
        "idx_button_main_menu_id", "buttons", ["main_menu_id"], unique=False
    )
    op.create_index(
        "idx_button_reply_text", "buttons", ["reply_text"], unique=False
    )
    op.create_index(
        "idx_chainbutton_next_step_id",
        "chain_buttons",
        ["next_step_id"],
        unique=False,
    )
    op.create_index(
        "idx_chainbutton_step_id", "chain_buttons", ["step_id"], unique=False
    )
    op.create_index(
        "idx_chainbutton_text_step_id",
        "chain_buttons",
        ["text", "step_id"],
        unique=False,
    )
    op.create_index(
        "idx_chainstep_chain_id", "chain_steps", ["chain_id"], unique=False
    )
    op.create_index(
        "idx_chainstep_name", "chain_steps", ["name"], unique=False
    )
    op.create_index(
        "idx_chainstep_next_step_id",
        "chain_steps",
        ["next_step_id"],
        unique=False,
    )
    op.create_index("idx_chain_bot_id", "chains", ["bot_id"], unique=False)
    op.create_index(
        "idx_chain_first_step", "chains", ["first_chain_step_id"], unique=False
    )
    op.create_index(
        "idx_chain_name_bot_id", "chains", ["name", "bot_id"], unique=False
    )
    op.create_index("idx_mainmenu_bot", "main_menu", ["bot_id"], unique=True)
    op.create_index(
        "idx_mainmenu_welcome_message",
        "main_menu",
        ["welcome_message"],
        unique=False,
    )
    op.create_index(
        "idx_userstate_updated_at", "user_state", ["updated_at"], unique=False
    )
    op.create_index(
        "idx_userstate_user_bot",
        "user_state",
        ["user_id", "bot_id"],
        unique=False,
    )
    op.create_index(
        "idx_userstate_user_expects",
        "user_state",
        ["user_id", "expects_text_input"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_userstate_user_expects", table_name="user_state")
    op.drop_index("idx_userstate_user_bot", table_name="user_state")
    op.drop_index("idx_userstate_updated_at", table_name="user_state")
    op.drop_index("idx_mainmenu_welcome_message", table_name="main_menu")
    op.drop_index("idx_mainmenu_bot", table_name="main_menu")
    op.drop_index("idx_chain_name_bot_id", table_name="chains")
    op.drop_index("idx_chain_first_step", table_name="chains")
    op.drop_index("idx_chain_bot_id", table_name="chains")
    op.drop_index("idx_chainstep_next_step_id", table_name="chain_steps")
    op.drop_index("idx_chainstep_name", table_name="chain_steps")
    op.drop_index("idx_chainstep_chain_id", table_name="chain_steps")
    op.drop_index("idx_chainbutton_text_step_id", table_name="chain_buttons")
    op.drop_index("idx_chainbutton_step_id", table_name="chain_buttons")
    op.drop_index("idx_chainbutton_next_step_id", table_name="chain_buttons")
    op.drop_index("idx_button_reply_text", table_name="buttons")
    op.drop_index("idx_button_main_menu_id", table_name="buttons")
    op.drop_index("idx_button_chain", table_name="buttons")
    op.drop_index("idx_button_bot_text", table_name="buttons")
    op.drop_constraint(None, "bots", type_="unique")  # type: ignore
    op.drop_index("idx_bot_username", table_name="bots")
    op.drop_index("idx_bot_token", table_name="bots")
    op.create_index("ix_bots_token", "bots", ["token"], unique=True)
    op.drop_index("idx_botuser_created_at", table_name="bot_users")
    # ### end Alembic commands ###
