"""Remove callback from chain button

Revision ID: 5febed5bc02d
Revises: 18823ad12e42
Create Date: 2025-03-30 12:20:38.327573

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5febed5bc02d"
down_revision: Union[str, None] = "18823ad12e42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chain_buttons", "callback")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chain_buttons",
        sa.Column(
            "callback", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
