"""Modife updated_at field 2

Revision ID: 72772ad1662b
Revises: 9862467a4144
Create Date: 2025-03-17 19:41:34.911806

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "72772ad1662b"
down_revision: Union[str, None] = "9862467a4144"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
