"""Fix main menu fields

Revision ID: 7c86754d79fb
Revises: 76c134ca1de0
Create Date: 2025-04-06 07:54:06.811241

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7c86754d79fb"
down_revision: Union[str, None] = "76c134ca1de0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "bot_users_bot_id_fkey", "bot_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        source_schema="public",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "bot_users", schema="public", type_="foreignkey"  # type:ignore
    )  # type:ignore
    op.create_foreign_key(
        "bot_users_bot_id_fkey",
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
