"""Fix name field of Chain

Revision ID: 8759c94d0e89
Revises: c05b98c723ba
Create Date: 2025-03-20 10:02:59.206674

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8759c94d0e89"
down_revision: Union[str, None] = "c05b98c723ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "chains", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chains", type_="unique")  # type: ignore
    # ### end Alembic commands ###
