"""Add name to chain_step

Revision ID: 974e5f098b7c
Revises: 457df28faa66
Create Date: 2025-03-23 16:38:25.162407

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "974e5f098b7c"
down_revision: Union[str, None] = "457df28faa66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chain_steps", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chain_steps", "name")
    # ### end Alembic commands ###
