"""Modife updated_at field

Revision ID: 9862467a4144
Revises: c3e50d97325c
Create Date: 2025-03-17 19:28:23.682739

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9862467a4144"
down_revision: Union[str, None] = "c3e50d97325c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
