"""Fix chain models

Revision ID: 98a815bebf84
Revises: a13ebc63143a
Create Date: 2025-04-17 12:22:07.124762

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "98a815bebf84"
down_revision: Union[str, None] = "a13ebc63143a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "bot_users_bot_id_fkey", "bot_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        source_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "chain_buttons_step_id_fkey", "chain_buttons", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "chain_buttons",
        "chain_steps",
        ["step_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_chain_steps_chain_id", "chain_steps", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "chain_steps", "chains", ["chain_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chain_steps", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "fk_chain_steps_chain_id",
        "chain_steps",
        "chains",
        ["chain_id"],
        ["id"],
    )
    op.drop_constraint(None, "chain_buttons", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "chain_buttons_step_id_fkey",
        "chain_buttons",
        "chain_steps",
        ["step_id"],
        ["id"],
    )
    op.drop_constraint(None, "bot_users", schema="public", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "bot_users_bot_id_fkey",
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
