"""Add bot_id to button model

Revision ID: b155eafa2da8
Revises: ed0f567408e9
Create Date: 2025-03-08 12:56:52.796747

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b155eafa2da8"
down_revision: Union[str, None] = "ed0f567408e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("buttons", sa.Column("bot_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "buttons", "bots", ["bot_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "buttons", type_="foreignkey")  # type:ignore
    op.drop_column("buttons", "bot_id")
    # ### end Alembic commands ###
