"""Remove chain's start message

Revision ID: c05b98c723ba
Revises: 7f4d208b12b3
Create Date: 2025-03-20 06:22:54.512509

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c05b98c723ba"
down_revision: Union[str, None] = "7f4d208b12b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chains", "start_message")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chains",
        sa.Column(
            "start_message", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
