"""Add Main menu

Revision ID: c0cd6f7e27a1
Revises: c79844968951
Create Date: 2025-03-08 10:27:07.952127

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c0cd6f7e27a1"
down_revision: Union[str, None] = "c79844968951"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funnel_buttons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("next_step_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["next_step_id"],
            ["funnel_steps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["funnel_steps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_funnel_buttons_id"), "funnel_buttons", ["id"], unique=False
    )
    op.create_table(
        "main_menu",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("welcome_message", sa.String(length=3000), nullable=False),
        sa.Column("button_id", sa.Integer(), nullable=True),
        sa.Column("bot_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["button_id"],
            ["buttons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_main_menu_id"), "main_menu", ["id"], unique=False)
    op.drop_index("ix_commands_id", table_name="commands")
    op.drop_table("commands")
    op.add_column(
        "buttons",
        sa.Column("button_text", sa.String(length=64), nullable=False),
    )
    op.add_column(
        "buttons",
        sa.Column("reply_text", sa.String(length=3000), nullable=True),
    )
    op.add_column(
        "buttons", sa.Column("funnel_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "buttons", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "buttons", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    op.drop_constraint(
        "buttons_next_step_id_fkey", "buttons", type_="foreignkey"
    )
    op.drop_constraint("buttons_step_id_fkey", "buttons", type_="foreignkey")
    op.create_foreign_key(None, "buttons", "funnels", ["funnel_id"], ["id"])
    op.drop_column("buttons", "text")
    op.drop_column("buttons", "next_step_id")
    op.drop_column("buttons", "step_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "buttons",
        sa.Column("step_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "buttons",
        sa.Column(
            "next_step_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "buttons",
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "buttons", type_="foreignkey")  # type:ignore
    op.create_foreign_key(
        "buttons_step_id_fkey", "buttons", "funnel_steps", ["step_id"], ["id"]
    )
    op.create_foreign_key(
        "buttons_next_step_id_fkey",
        "buttons",
        "funnel_steps",
        ["next_step_id"],
        ["id"],
    )
    op.drop_column("buttons", "updated_at")
    op.drop_column("buttons", "created_at")
    op.drop_column("buttons", "funnel_id")
    op.drop_column("buttons", "reply_text")
    op.drop_column("buttons", "button_text")
    op.create_table(
        "commands",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("command", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "response", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("bot_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name="commands_bot_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="commands_pkey"),
    )
    op.create_index("ix_commands_id", "commands", ["id"], unique=False)
    op.drop_index(op.f("ix_main_menu_id"), table_name="main_menu")
    op.drop_table("main_menu")
    op.drop_index(op.f("ix_funnel_buttons_id"), table_name="funnel_buttons")
    op.drop_table("funnel_buttons")
    # ### end Alembic commands ###
