"""Update chain_step

Revision ID: c3e50d97325c
Revises: e251863f765e
Create Date: 2025-03-17 11:07:43.192296

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c3e50d97325c"
down_revision: Union[str, None] = "e251863f765e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chain_steps", sa.Column("next_step_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "chain_steps", "chain_steps", ["next_step_id"], ["id"]
    )
    op.add_column(
        "user_state",
        sa.Column("expects_text_input", sa.Boolean(), nullable=True),
    )
    op.add_column("user_state", sa.Column("result", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_state", "result")
    op.drop_column("user_state", "expects_text_input")
    op.drop_constraint(None, "chain_steps", type_="foreignkey")  # type: ignore
    op.drop_column("chain_steps", "next_step_id")
    # ### end Alembic commands ###
