"""Fix delete chain

Revision ID: c600e7f341b4
Revises: d3ca3549d984
Create Date: 2025-04-17 22:35:19.074632

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c600e7f341b4"
down_revision: Union[str, None] = "d3ca3549d984"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "bot_users_bot_id_fkey", "bot_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        source_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint("buttons_chain_id_fkey", "buttons", type_="foreignkey")
    op.create_foreign_key(
        None, "buttons", "chains", ["chain_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "buttons", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "buttons_chain_id_fkey", "buttons", "chains", ["chain_id"], ["id"]
    )
    op.drop_constraint(None, "bot_users", schema="public", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "bot_users_bot_id_fkey",
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
