"""Update default_reply field to bot model

Revision ID: c79844968951
Revises: 40e112d2ab18
Create Date: 2025-03-05 20:05:19.492560

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c79844968951"
down_revision: Union[str, None] = "40e112d2ab18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
