"""Fix chain delete bot cascade

Revision ID: d3ca3549d984
Revises: fee2a9c89623
Create Date: 2025-04-17 20:51:30.776370

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d3ca3549d984"
down_revision: Union[str, None] = "fee2a9c89623"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "bot_users_bot_id_fkey", "bot_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        source_schema="public",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "user_state_bot_id_fkey", "user_state", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "user_state", "bots", ["bot_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_state", type_="foreignkey")  # type:ignore
    op.create_foreign_key(
        "user_state_bot_id_fkey", "user_state", "bots", ["bot_id"], ["id"]
    )
    op.drop_constraint(None, "bot_users", schema="public", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "bot_users_bot_id_fkey",
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
