"""Add timestamp to user state

Revision ID: e251863f765e
Revises: d8cbbebc5224
Create Date: 2025-03-16 21:28:53.455789

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e251863f765e"
down_revision: Union[str, None] = "d8cbbebc5224"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_state", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "user_state", sa.Column("updated_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_state", "updated_at")
    op.drop_column("user_state", "created_at")
    # ### end Alembic commands ###
