"""Fix main menu buttons

Revision ID: ed0f567408e9
Revises: c0cd6f7e27a1
Create Date: 2025-03-08 11:39:44.679059

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ed0f567408e9"
down_revision: Union[str, None] = "c0cd6f7e27a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "buttons", sa.Column("main_menu_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "buttons", "main_menu", ["main_menu_id"], ["id"]
    )
    op.alter_column(
        "main_menu", "bot_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        "main_menu_button_id_fkey", "main_menu", type_="foreignkey"
    )
    op.drop_column("main_menu", "button_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "main_menu",
        sa.Column(
            "button_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "main_menu_button_id_fkey",
        "main_menu",
        "buttons",
        ["button_id"],
        ["id"],
    )
    op.alter_column(
        "main_menu", "bot_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(None, "buttons", type_="foreignkey")  # type:ignore
    op.drop_column("buttons", "main_menu_id")
    # ### end Alembic commands ###
