"""Add text_input field to chain step

Revision ID: ed152b883501
Revises: 72772ad1662b
Create Date: 2025-03-17 20:12:45.763775

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ed152b883501"
down_revision: Union[str, None] = "72772ad1662b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chain_steps", sa.Column("text_input", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chain_steps", "text_input")
    # ### end Alembic commands ###
