"""Fix bot cascade delete

Revision ID: fee2a9c89623
Revises: 98a815bebf84
Create Date: 2025-04-17 12:27:52.729306

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fee2a9c89623"
down_revision: Union[str, None] = "98a815bebf84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "bot_users_bot_id_fkey", "bot_users", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        source_schema="public",
        ondelete="CASCADE",
    )
    op.alter_column(
        "buttons", "bot_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index("ix_buttons_bot_id", table_name="buttons")
    op.drop_constraint("buttons_bot_id_fkey", "buttons", type_="foreignkey")
    op.create_foreign_key(
        None, "buttons", "bots", ["bot_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("fk_chains_bot_id", "chains", type_="foreignkey")
    op.create_foreign_key(
        None, "chains", "bots", ["bot_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chains", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "fk_chains_bot_id", "chains", "bots", ["bot_id"], ["id"]
    )
    op.drop_constraint(None, "buttons", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "buttons_bot_id_fkey", "buttons", "bots", ["bot_id"], ["id"]
    )
    op.create_index("ix_buttons_bot_id", "buttons", ["bot_id"], unique=False)
    op.alter_column(
        "buttons", "bot_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(None, "bot_users", schema="public", type_="foreignkey")  # type: ignore
    op.create_foreign_key(
        "bot_users_bot_id_fkey",
        "bot_users",
        "bots",
        ["bot_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
