from django.urls import path

from .views import (
    BotChainDetailView,
    BotChainsResultView,
    BotChainView,
    ChainResultsView,
    CreateChainButtonView,
    CreateChainStepTextinputView,
    CreateChainStepView,
    CreateChainView,
    DeleteChainButtonView,
    DeleteChainStepView,
    DeleteChainView,
    EditTextinputView,
    UpdateChainButtonView,
    UpdateChainStepView,
    UpdateChainView,
)


urlpatterns = [
    path(
        "chains/<int:bot_id>/",
        BotChainView.as_view(),
        name="bot-chains",
    ),
    path(
        "chain/<int:bot_id>/<int:chain_id>",
        BotChainDetailView.as_view(),
        name="bot-chain",
    ),
    path(
        "chain/<int:bot_id>",
        CreateChainView.as_view(),
        name="create-chain",
    ),
    path(
        "update-chain/<int:bot_id>/<int:chain_id>",
        UpdateChainView.as_view(),
        name="update-chain",
    ),
    path(
        "delete-chain/<int:bot_id>/<int:chain_id>",
        DeleteChainView.as_view(),
        name="delete-chain",
    ),
    path(
        "create-chain-step/<int:bot_id>/<int:chain_id>",
        CreateChainStepView.as_view(),
        name="create-chain-step",
    ),
    path(
        "create-chain-step-textinput/<int:bot_id>/<int:chain_id>",
        CreateChainStepTextinputView.as_view(),
        name="create-chain-step-textinput",
    ),
    path(
        "update-chain-step/<int:bot_id>/<int:chain_id>/<int:step_id>",
        UpdateChainStepView.as_view(),
        name="update-chain-step",
    ),
    path(
        "delete-chain-step/<int:bot_id>/<int:chain_id>/<int:step_id>",
        DeleteChainStepView.as_view(),
        name="delete-chain-step",
    ),
    path(
        "edit-text-input/<int:bot_id>/<int:chain_id>/<int:step_id>",
        EditTextinputView.as_view(),
        name="edit-text-input",
    ),
    path(
        "create-chain-button/<int:bot_id>/<int:chain_id>",
        CreateChainButtonView.as_view(),
        name="create-chain-button",
    ),
    path(
        "update-chain-button/<int:bot_id>/<int:chain_id>/<int:button_id>",
        UpdateChainButtonView.as_view(),
        name="update-chain-button",
    ),
    path(
        "delete-chain-button/<int:bot_id>/<int:chain_id>/<int:button_id>",
        DeleteChainButtonView.as_view(),
        name="delete-chain-button",
    ),
    path(
        "chain-results/<int:bot_id>/<int:chain_id>/",
        ChainResultsView.as_view(),
        name="chain-results",
    ),
    path(
        "bot-chains-results/<int:bot_id>/",
        BotChainsResultView.as_view(),
        name="bot-chains-results",
    ),
]
