from django.urls import include, path

from .views import (
    BotChainDetailView,
    BotChainsResultView,
    BotChainView,
    ChainResultsView,
    CreateChainButtonView,
    CreateChainStepTextinputView,
    CreateChainStepView,
    CreateChainView,
    DeleteChainButtonView,
    DeleteChainStepView,
    DeleteChainView,
    EditTextinputView,
    UpdateChainButtonView,
    UpdateChainStepView,
    UpdateChainView,
)


urlpatterns = [
    path(
        "bots/<int:bot_id>/chains/",
        include(
            [
                path("", BotChainView.as_view(), name="chain-list"),
                path(
                    "results/",
                    BotChainsResultView.as_view(),
                    name="chain-results-list",
                ),
                path(
                    "create/", CreateChainView.as_view(), name="chain-create"
                ),
                path(
                    "<int:chain_id>/",
                    include(
                        [
                            path(
                                "",
                                BotChainDetailView.as_view(),
                                name="chain-detail",
                            ),
                            path(
                                "update/",
                                UpdateChainView.as_view(),
                                name="chain-update",
                            ),
                            path(
                                "delete/",
                                DeleteChainView.as_view(),
                                name="chain-delete",
                            ),
                            path(
                                "results/",
                                ChainResultsView.as_view(),
                                name="chain-results",
                            ),
                            path(
                                "steps/",
                                include(
                                    [
                                        path(
                                            "create/",
                                            CreateChainStepView.as_view(),
                                            name="step-create",
                                        ),
                                        path(
                                            "create-text-input/",
                                            CreateChainStepTextinputView.as_view(),
                                            name="step-create-text",
                                        ),
                                        path(
                                            "<int:step_id>/",
                                            include(
                                                [
                                                    path(
                                                        "",
                                                        UpdateChainStepView.as_view(),
                                                        name="step-detail",
                                                    ),
                                                    path(
                                                        "delete/",
                                                        DeleteChainStepView.as_view(),
                                                        name="step-delete",
                                                    ),
                                                    path(
                                                        "edit-text-input/",
                                                        EditTextinputView.as_view(),
                                                        name="step-edit-text-input",
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            path(
                                "buttons/",
                                include(
                                    [
                                        path(
                                            "create/",
                                            CreateChainButtonView.as_view(),
                                            name="button-create",
                                        ),
                                        path(
                                            "<int:button_id>/",
                                            include(
                                                [
                                                    path(
                                                        "",
                                                        UpdateChainButtonView.as_view(),
                                                        name="button-detail",
                                                    ),
                                                    path(
                                                        "delete/",
                                                        DeleteChainButtonView.as_view(),
                                                        name="button-delete",
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
]
